# Minimum golangci-lint version required: v1.42.0
run:
  go: "1.17"
  timeout: 3m
  skip-dirs:
    - tmp

linters-settings:
  gci:
    sections:
      - prefix(github.com/foomo/keel)
  revive:
    rules:
      - name: indent-error-flow
        disabled: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-tags:
      - experimental
      - opinionated
    disabled-checks:
      - ifElseChain
    settings:
      hugeParam:
        sizeThreshold: 512

linters:
  enable:
    - bodyclose
    - dogsled
    - exportloopref
    # - gci TODO re-enable
    - goconst
    - gocritic
    # - gocyclo
    - gofmt
    - goprintffuncname
    #- gosec
    - ifshort
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
