package middleware

import (
	"net/http"
	"strings"

	keelhttp "github.com/foomo/keel/net/http"
	semconv "go.opentelemetry.io/otel/semconv/v1.41.0"
	"go.opentelemetry.io/otel/trace"
	"go.uber.org/zap"

	keelhttpcontext "github.com/foomo/keel/net/http/context"
	"github.com/foomo/keel/net/http/provider"
)

type (
	// RequestIDOptions configures the [RequestID] middleware.
	RequestIDOptions struct {
		// Provider generates a request ID when the request carries none.
		Provider provider.RequestID
		// RequestHeader lists the request headers checked in order; the first
		// non-empty value is used.
		RequestHeader []string
		// ResponseHeader is the name of the header the ID is written to.
		ResponseHeader string
		// SetRequestHeader reports whether the ID is set on the request,
		// using the ResponseHeader name.
		SetRequestHeader bool
		// SetResponseHeader reports whether the ID is added to the response
		// unless the header is already present.
		SetResponseHeader bool
		// SetContext reports whether the ID is stored in the request context.
		SetContext bool
	}
	// RequestIDOption configures [RequestIDOptions].
	RequestIDOption func(*RequestIDOptions)
)

// GetDefaultRequestIDOptions returns the default options, which read the
// X-Request-ID and Cf-Ray headers, write X-Request-ID and enable all Set
// flags.
func GetDefaultRequestIDOptions() RequestIDOptions {
	return RequestIDOptions{
		Provider:          provider.DefaultRequestID,
		RequestHeader:     []string{"X-Request-ID", "Cf-Ray"},
		ResponseHeader:    "X-Request-ID",
		SetRequestHeader:  true,
		SetResponseHeader: true,
		SetContext:        true,
	}
}

// RequestIDWithRequestHeader appends headers to
// [RequestIDOptions.RequestHeader].
func RequestIDWithRequestHeader(v ...string) RequestIDOption {
	return func(o *RequestIDOptions) {
		o.RequestHeader = append(o.RequestHeader, v...)
	}
}

// RequestIDWithResponseHeader sets [RequestIDOptions.ResponseHeader].
// Defaults to X-Request-ID.
func RequestIDWithResponseHeader(v string) RequestIDOption {
	return func(o *RequestIDOptions) {
		o.ResponseHeader = v
	}
}

// RequestIDWithSetRequestHeader sets [RequestIDOptions.SetRequestHeader].
// Defaults to true.
func RequestIDWithSetRequestHeader(v bool) RequestIDOption {
	return func(o *RequestIDOptions) {
		o.SetRequestHeader = v
	}
}

// RequestIDWithSetResponseHeader sets [RequestIDOptions.SetResponseHeader].
// Defaults to true.
func RequestIDWithSetResponseHeader(v bool) RequestIDOption {
	return func(o *RequestIDOptions) {
		o.SetResponseHeader = v
	}
}

// RequestIDWithGenerator sets [RequestIDOptions.Provider]. Defaults to
// [provider.DefaultRequestID].
func RequestIDWithGenerator(v provider.RequestID) RequestIDOption {
	return func(o *RequestIDOptions) {
		o.Provider = v
	}
}

// RequestIDWithSetContext sets [RequestIDOptions.SetContext]. Defaults to true.
func RequestIDWithSetContext(v bool) RequestIDOption {
	return func(o *RequestIDOptions) {
		o.SetContext = v
	}
}

// RequestID returns a middleware that ensures every request has an ID, taken
// from the first non-empty configured request header or generated by the
// provider, and propagates it to the request, response and context.
func RequestID(opts ...RequestIDOption) keelhttp.Middleware {
	options := GetDefaultRequestIDOptions()

	for _, opt := range opts {
		if opt != nil {
			opt(&options)
		}
	}

	return RequestIDWithOptions(options)
}

// RequestIDWithOptions is like [RequestID] but takes fully populated options.
func RequestIDWithOptions(opts RequestIDOptions) keelhttp.Middleware {
	return func(l *zap.Logger, name string, next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			span := trace.SpanFromContext(r.Context())
			if span.IsRecording() {
				span.AddEvent("RequestID")
			}

			var (
				key       string
				requestID string
			)
			for _, value := range opts.RequestHeader {
				if requestID = r.Header.Get(value); requestID != "" {
					key = value
					break
				}
			}

			if requestID == "" {
				requestID = opts.Provider()
			}

			if span.IsRecording() && key != "" && requestID != "" {
				span.SetAttributes(semconv.HTTPRequestHeader(strings.ToLower(key), requestID))
			}

			if requestID != "" && opts.SetContext {
				r = r.WithContext(keelhttpcontext.SetRequestID(r.Context(), requestID))
			}

			if requestID != "" && opts.SetRequestHeader {
				r.Header.Set(opts.ResponseHeader, requestID)
			}

			if requestID != "" && opts.SetResponseHeader {
				if value := w.Header().Get(opts.ResponseHeader); value == "" {
					w.Header().Add(opts.ResponseHeader, requestID)
				}
			}

			next.ServeHTTP(w, r)
		})
	}
}
