# This workflow runs all dockerfiles in this repo
name: checks

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GO_VERSION: 1.17
  GOLANGCI_LINT_VERSION: v1.43.0

jobs:
  matrix:
    name: go matrix
    runs-on: ubuntu-latest
    outputs:
      gomod: ${{ steps.gomod.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: gomod
        run: |
          matrix=$(find . -type f -name "go.mod" -print0 | xargs -0 -n1 dirname | sort --unique | jq -R -s -c 'split("\n")[:-1]')
          echo "${matrix}"
          echo "::set-output name=matrix::${matrix}"
  go_lint:
    name: go lint
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gomod: ${{ fromJson(needs.matrix.outputs.gomod) }}
    env:
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.gomod }}
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v4.8.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_GO: false
#      - run: go test -v ./...
